project:
  type: book
  output-dir: docs

book:
  title: "LinkedIn for Academics"
  author:
    - "Emily Nordmann"
  date: "January 2026"
  chapters:
    - index.qmd
    - 01-why-linkedin.qmd
    - 02-linkedin-basics.qmd
    - 03-content.qmd
    - 04-teaching-learning.qmd
    - 05-oer.qmd
    - 06-self-care.qmd
    - 07-bootcamp.qmd
  sidebar:
    style: floating
    search: true

format:
  html:
    theme:
      light: cosmo
      dark: slate
    toc: true
    include-in-header:
      - text: |
          <script data-goatcounter="https://emilynordmann.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>